#kivy file
<FirstScreen>: # same class name
    GridLayout:
        cols: 1
	padding: 10
	spacing: 10
	Image:
  	    #source: 'files/sunny.jpg'
	    id: img
	    size_hint_y: 0.8
	TextInput:
	    id: user_query
	    size_hint_y: 0.1
	Button:
	    text: 'Search Image'
	    size_hint_y: 0.1
	    #on_press: root.search_image() #current instance
	    on_press: root.set_image()

<RootWidget>:
    FirstScreen:
	id: first_screen
	name: 'first_screen'


#<SecondScreen>:
#    Image:
#    Button:

