#! /bin/bash

old_IFS="$IFS";
IFS=":";

echo "***************** PATH SCRIPT **************"

if [ "$1" == "-d" ]; then
	my_dir="$2";
	for dir in $PATH;
	do
		if [ "$my_dir" == "$dir" -o "$my_dir" == "$dir/" ]; then
			echo "#### FOUND"
		fi
	done
fi

if [ "$1" == "-c" ]; then
	my_com="$2"
	for dir in $PATH;
	do
		if [ -e "$dir/$my_com" ]; then
			echo "**** Command PRESENT in PATH***"
			echo "$dir/$my_com"
		fi
	done
fi

if [ "$1" == "" ]; then
	for dir in $PATH;
	do
		echo "$dir"
	done
fi
IFS="$old_IFS"
