#! /bin/bash

# stat -f $Sm calc | cut -c 08-09
# stat -f $Sm * | cut -c 08-09

dir="$1"

if [ ! -d $dir ]; then
	echo "NOT DIR"
	exit
fi

# Unix
#cont_files=$(stat -f $Sm $dir/* | cut -c 08-09)
# ubnutu
#cont_files=$(stat -c %y $dir/* | cut -c 12-13)


if [ $OSTYPE == "linux-gnu ]]; then
	echo "we are in linux"
	cont_files=$(stat -c %y $dir/* | cut -c 12-13)
fi
if [ $OSTYPE == "darwin"* ]]; then
	echo "we are in MAC"
	cont_files=$(stat -f $Sm $dir/* | cut -c 08-09)
fi


echo $cont_files

for k in {0..23};
do
	hours[k]=0;
done

echo ${hours[@]}

for i in $cont_files;
do
	#echo $i value too great for base (error token is "08")
	# 08 -> 8
	j=${i#0}
	(( hours[i]=${hours[i]}+1))

done

echo -e "Hours \t Files \t\t Hours \t Files"
echo -e "----- \t ----- \t\t ----- \t -----"

#for k in {0..23};
#do
#	echo -e "$k \t ${hours[k]}"
#done

for k in {0..11};
do
	m=$(( $k+12 ))
	echo -e "$k \t ${hours[k]} \t\t $m \t ${hours[m]} "
done


echo $OSTYPE
# linux-gnu Ubuntu
# darwin17 MAC
# cygwin emulator in win
